---
title: "Advice for workflows with `recountmethylation` data objects and `DelayedArray`"
author:
  - name: Sean K. Maden
  - name: Reid F. Thompson
  - name: Kasper D. Hansen
  - name: Abhi Nellore
package: recountmethylation
abstract: >
   Recommendations for data management and preprocessing tasks that effectively 
   utilize `DelayedArray` technology.
vignette: >
    %\VignetteDepends{RCurl}
    %\VignetteEngine{knitr::knitr} 
    %\VignetteIndexEntry{recountmethylation DelayedArray} 
    %\usepackage[UTF-8]{inputenc}
output:
    BiocStyle::html_document:
        toc: true
        tocfloat: true
        code_folding: show
    pdf_document: default
---

```{r setup, echo = FALSE}
suppressMessages(library(HDF5Array))
suppressMessages(library(minfi))
knitr::opts_chunk$set(eval = TRUE, echo = TRUE, 
                      warning = FALSE, message = FALSE)

# recountmethylation
library(recountmethylation)

# load test data
testdatdn <- "remethdb_h5se-test_gr_00-00-01_1583780004"
datpath <- system.file("extdata", testdatdn, package = "recountmethylation")
h5gr <- loadHDF5SummarizedExperiment(datpath)

```

# Tests standard preprocessing operations

## Data retrieval

## Data analysis

# Differential methylation



```{r}

mset <- mapToGenome(h5gm)

path <- ""
h5rg <- loadHDF5SummarizedExperiment("")
pill <- preprocessIllumina(h5rg)
pnoob <- preprocessNoob(pill)
cb <- ComBat(pnoob)


```




# Session info

```{r}
sessionInfo()
```


# 